@url_dev=http://localhost:3052/v1/api/product

POST {{url_dev}}
Content-Type: application/json
x-api-key: 244e3b0e35c668530c0c6b2e3ad5868cb7b80fbbcb7df04675eb6e9caa35f28011027e5976070bc7220961ec0f9168b85dd60b248dc899658a36c10f6212ae6c
x-client-id: 66686d085475ccb674d81ad9
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY4NmQwODU0NzVjY2I2NzRkODFhZDkiLCJlbWFpbCI6InNob3B0aXBzMDFAZ21haWwuY29tIiwiaWF0IjoxNzE4NTEwODcwLCJleHAiOjE3MTg2ODM2NzB9.Rx18gEqLTO0wNxJAp0T4AEU09J4eL6cvlUJjlYj5q_c

{
    "product_name": "New Jeans",
    "product_description": "High-quality denim jeans",
    "product_price": 50,
    "product_shop": "66686d085475ccb674d81ad9",
    "product_type": "Clothing",
    "product_thumb": "product_thumb",
    "product_quantity": 5,
    "product_attributes": {
        "brand": "Levi's",
        "size": "L",
        "material": "Denim"
    }
}
